// examples/with-vue/src/Message.vue
<script setup lang="ts">
import { MessagePrimitiveParts, useAuiState } from "@assistant-ui/vue";
import type {} from "@assistant-ui/core/store";

const role = useAuiState((s) => s.message.role);
const pulsing = useAuiState(
  (s) => s.message.content.length === 0 && s.thread.isRunning,
);
</script>

<template>
  <li v-if="role === 'user'" data-role="user" class="flex justify-end px-2">
    <div
      class="bg-muted text-foreground max-w-[80%] rounded-xl px-4 py-2 wrap-break-word"
    >
      <MessagePrimitiveParts />
    </div>
  </li>
  <li
    v-else
    data-role="assistant"
    class="text-foreground px-2 leading-relaxed wrap-break-word"
  >
    <MessagePrimitiveParts />
    <span v-if="pulsing" class="animate-pulse">…</span>
  </li>
</template>

// examples/with-svelte/src/Message.svelte
<script lang="ts">
  import type { ThreadMessage } from "@assistant-ui/core";

  let { message }: { message: ThreadMessage } = $props();

  const text = $derived(
    message.content
      .map((part) => (part.type === "text" ? part.text : ""))
      .join(""),
  );
</script>

<li
  data-role={message.role}
  class={[
    "group flex flex-col gap-1",
    message.role === "user" ? "items-end" : "items-start",
  ].join(" ")}
>
  <div
    class={[
      "px-2 wrap-break-word",
      message.role === "user"
        ? "bg-muted text-foreground max-w-[80%] rounded-xl px-4 py-2"
        : "text-foreground leading-relaxed",
    ].join(" ")}
  >
    <p class="whitespace-pre-line">{text}</p>
  </div>
</li>
