// examples/with-svelte/src/Message.svelte
<script lang="ts">
  import type { MessageState } from "@assistant-ui/core/store";
  import {
    actionBarCopy,
    actionBarEdit,
    actionBarReload,
    branchPickerNext,
    branchPickerPrevious,
    composerCancel,
    composerInput,
    composerSend,
    useAuiState,
    type MessageItem,
  } from "@assistant-ui/svelte";
  import {
    CheckIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    CopyIcon,
    PencilIcon,
    RefreshCwIcon,
  } from "@lucide/svelte";

  let { message, item }: { message: MessageState; item: MessageItem } =
    $props();

  const text = $derived(
    message.content
      .map((part) => (part.type === "text" ? part.text : ""))
      .join(""),
  );

  const isEditing = useAuiState((s) => s.composer.isEditing, { item });
  const branchNumber = useAuiState((s) => s.message.branchNumber, { item });
  const branchCount = useAuiState((s) => s.message.branchCount, { item });
  const edit = actionBarEdit({ item });
  const copy = actionBarCopy({ item });
  const reload = actionBarReload({ item });
  const previous = branchPickerPrevious({ item });
  const next = branchPickerNext({ item });
  const editInput = composerInput({ item });
  const editSend = composerSend({ item });
  const editCancel = composerCancel({ item });
</script>

<li
  data-role={message.role}
  class={[
    "group flex flex-col gap-1",
    message.role === "user" ? "items-end" : "items-start",
  ].join(" ")}
>
  {#if isEditing.current}
    <div
      class="border-border/60 flex w-full max-w-[80%] flex-col gap-2 rounded-xl border p-2"
    >
      <textarea
        {...editInput.props}
        class="w-full resize-none bg-transparent px-1 py-0.5 outline-none"
        aria-label="Edit message"
        rows="2"
      ></textarea>
      <div class="flex justify-end gap-2 text-sm">
        <button
          {...editCancel.props}
          class="text-muted-foreground rounded-lg px-2 py-1"
        >
          Discard
        </button>
        <button
          {...editSend.props}
          class="bg-primary text-primary-foreground rounded-lg px-2 py-1 disabled:opacity-50"
        >
          Save
        </button>
      </div>
    </div>
  {:else}
    <div
      class={[
        "px-2 wrap-break-word",
        message.role === "user"
          ? "bg-muted text-foreground max-w-[80%] rounded-xl px-4 py-2"
          : "text-foreground leading-relaxed",
      ].join(" ")}
    >
      <p class="whitespace-pre-line">{text}</p>
    </div>
  {/if}
  <div
    class="text-muted-foreground flex items-center gap-1 px-2 opacity-0 transition-opacity group-hover:opacity-100 focus-within:opacity-100 [@media(hover:none)]:opacity-100"
  >
    {#if message.role === "user"}
      <button
        {...edit.props}
        class="hover:text-foreground rounded p-1"
        aria-label="Edit"
      >
        <PencilIcon class="size-3.5" />
      </button>
    {/if}
    <button
      {...copy.props}
      class="hover:text-foreground rounded p-1"
      aria-label="Copy"
    >
      {#if copy.isCopied}
        <CheckIcon class="size-3.5" />
      {:else}
        <CopyIcon class="size-3.5" />
      {/if}
    </button>
    {#if message.role === "assistant"}
      <button
        {...reload.props}
        class="hover:text-foreground rounded p-1"
        aria-label="Regenerate"
      >
        <RefreshCwIcon class="size-3.5" />
      </button>
    {/if}
    {#if branchCount.current > 1}
      <span class="flex items-center gap-0.5 text-xs">
        <button
          {...previous.props}
          class="hover:text-foreground rounded p-0.5 disabled:opacity-40"
          aria-label="Previous branch"
        >
          <ChevronLeftIcon class="size-3.5" />
        </button>
        {branchNumber.current} / {branchCount.current}
        <button
          {...next.props}
          class="hover:text-foreground rounded p-0.5 disabled:opacity-40"
          aria-label="Next branch"
        >
          <ChevronRightIcon class="size-3.5" />
        </button>
      </span>
    {/if}
  </div>
</li>

// examples/with-nuxt/app/components/Message.vue
<script setup lang="ts">
import {
  ActionBarPrimitiveCopy,
  ActionBarPrimitiveEdit,
  ActionBarPrimitiveReload,
  AuiIf,
  BranchPickerPrimitiveCount,
  BranchPickerPrimitiveNext,
  BranchPickerPrimitiveNumber,
  BranchPickerPrimitivePrevious,
  ComposerPrimitiveCancel,
  ComposerPrimitiveInput,
  ComposerPrimitiveSend,
  MessagePrimitiveParts,
  useAuiState,
} from "@assistant-ui/vue";
import type {} from "@assistant-ui/core/store";
import {
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CopyIcon,
  PencilIcon,
  RefreshCwIcon,
} from "@lucide/vue";

const role = useAuiState((s) => s.message.role);
const pulsing = useAuiState(
  (s) => s.message.content.length === 0 && s.thread.isRunning,
);
const editing = useAuiState((s) => s.composer.isEditing);
const copied = useAuiState((s) => s.message.isCopied);
const error = useAuiState((s) => {
  const message = s.message;
  if (
    message.role !== "assistant" ||
    message.status.type !== "incomplete" ||
    message.status.reason !== "error"
  ) {
    return null;
  }
  const value = message.status.error;
  if (typeof value === "string") return value;
  if (value && typeof value === "object" && "message" in value) {
    return String(value.message);
  }
  return "An error occurred.";
});
</script>

<template>
  <li
    :data-role="role"
    class="group flex flex-col gap-1"
    :class="role === 'user' ? 'items-end' : 'items-start'"
  >
    <div
      v-if="editing"
      class="border-border/60 flex w-full max-w-[80%] flex-col gap-2 rounded-xl border p-2"
    >
      <ComposerPrimitiveInput
        class="w-full resize-none bg-transparent px-1 py-0.5 outline-none"
        rows="2"
      />
      <div class="flex justify-end gap-2 text-sm">
        <ComposerPrimitiveCancel
          class="text-muted-foreground rounded-lg px-2 py-1"
        >
          Discard
        </ComposerPrimitiveCancel>
        <ComposerPrimitiveSend
          class="bg-primary text-primary-foreground rounded-lg px-2 py-1 disabled:opacity-50"
        >
          Save
        </ComposerPrimitiveSend>
      </div>
    </div>
    <div
      v-else
      class="px-2 wrap-break-word"
      :class="
        role === 'user'
          ? 'bg-muted text-foreground max-w-[80%] rounded-xl px-4 py-2'
          : 'text-foreground leading-relaxed'
      "
    >
      <MessagePrimitiveParts />
      <span v-if="pulsing" class="animate-pulse">…</span>
      <span v-if="error" class="text-destructive text-sm">{{ error }}</span>
    </div>
    <div
      class="text-muted-foreground flex items-center gap-1 px-2 opacity-0 transition-opacity group-hover:opacity-100 focus-within:opacity-100"
    >
      <ActionBarPrimitiveEdit
        v-if="role === 'user'"
        class="hover:text-foreground rounded p-1"
        aria-label="Edit"
      >
        <PencilIcon class="size-3.5" />
      </ActionBarPrimitiveEdit>
      <ActionBarPrimitiveCopy
        class="hover:text-foreground rounded p-1"
        aria-label="Copy"
      >
        <CheckIcon v-if="copied" class="size-3.5" />
        <CopyIcon v-else class="size-3.5" />
      </ActionBarPrimitiveCopy>
      <ActionBarPrimitiveReload
        v-if="role === 'assistant'"
        class="hover:text-foreground rounded p-1"
        aria-label="Regenerate"
      >
        <RefreshCwIcon class="size-3.5" />
      </ActionBarPrimitiveReload>
      <AuiIf :condition="(s) => s.message.branchCount > 1">
        <span class="flex items-center gap-0.5 text-xs">
          <BranchPickerPrimitivePrevious
            class="hover:text-foreground rounded p-0.5 disabled:opacity-40"
            aria-label="Previous branch"
          >
            <ChevronLeftIcon class="size-3.5" />
          </BranchPickerPrimitivePrevious>
          <BranchPickerPrimitiveNumber /> / <BranchPickerPrimitiveCount />
          <BranchPickerPrimitiveNext
            class="hover:text-foreground rounded p-0.5 disabled:opacity-40"
            aria-label="Next branch"
          >
            <ChevronRightIcon class="size-3.5" />
          </BranchPickerPrimitiveNext>
        </span>
      </AuiIf>
    </div>
  </li>
</template>
